insert into NOTICES_TEST (ID_NOTICE, CATEGORIE, UA, AUTEUR, COTE, TITRE)
SELECT trim(n1.DATACOL1) ID_NOTICE, trim(n1.datacol2) CATEGORIE, trim(n1.DATACOL3) UA, 
trim(n2.DATACOL2) AUTEUR, trim(n2.DATACOL3) COTE, trim(n2.DATACOL4) TITRE
FROM IMPORT1 n1 join IMPORT4 n2 ON n1.DATACOL1 = n2.DATACOL1;

INSERT INTO EXEMPLAIRES_TEST (ID_NOTICE, ID_EXEMPLAIRE, UA, STATUT)
SELECT trim(r.DATACOL1), trim(r.DATACOL2), trim(r.DATACOL3), trim(r.DATACOL4)
FROM IMPORT2 r;

// Insertion alternative des exemplaires
INSERT INTO EXEMPLAIRES 
SELECT trim(r.DATACOL1), trim(r.DATACOL2), trim(r.DATACOL3), trim(r.DATACOL4), null, null
FROM IMPORT3 r;